before_script:
  - shards install

cache:
  paths:
  - lib/

build:latest:
  image: "crystallang/crystal:latest"
  script:
  - crystal spec
  - crystal tool format --check
  - shards build

build:nightly:
  image: "crystallang/crystal:nightly"
  script:
  - crystal spec
  - crystal tool format --check
  - shards build

pages:
  image: "crystallang/crystal:latest"
  stage: deploy
  script:
  - crystal docs -o public src/pipelinecr.cr
  artifacts:
    paths:
    - public
  only:
  - master